/**
 * Perlin Noise Flow Field Generator
 * 
 * Creates beautiful flowing patterns using Perlin noise to drive particle movement
 */

import { Generator, GeneratorParameters, GenerationContext } from '../../core/Generator.js';
import { Color, PaletteGenerator, PALETTES } from '../../core/Color.js';
import { PerlinNoise, Vec2, MathUtils } from '../../utils/math.js';

interface Particle {
  position: Vec2;
  velocity: Vec2;
  age: number;
  maxAge: number;
  color: Color;
  trail: Vec2[];
}

export class PerlinFlowFieldGenerator extends Generator {
  constructor() {
    super('Perlin Flow Field', 'Particles follow vector fields generated by Perlin noise');
    
    this.parameters = {
      particleCount: {
        value: 2000,
        min: 500,
        max: 5000,
        description: 'Number of particles in the system',
        type: 'number'
      },
      noiseScale: {
        value: 0.005,
        min: 0.001,
        max: 0.02,
        description: 'Scale of the noise field',
        type: 'number'
      },
      flowStrength: {
        value: 2,
        min: 0.5,
        max: 5,
        description: 'Strength of the flow field',
        type: 'number'
      },
      trailLength: {
        value: 20,
        min: 5,
        max: 50,
        description: 'Length of particle trails',
        type: 'number'
      },
      palette: {
        value: 'ocean',
        options: Object.keys(PALETTES),
        description: 'Color palette for the artwork',
        type: 'select'
      },
      background: {
        value: 'dark',
        options: ['dark', 'light', 'transparent'],
        description: 'Background style',
        type: 'select'
      }
    } as GeneratorParameters;
  }

  protected generateFeatures(context: GenerationContext): Record<string, string | number> {
    const { random } = context;
    
    // Determine features based on parameters and randomness
    const particleCount = this.parameters.particleCount.value as number;
    const noiseScale = this.parameters.noiseScale.value as number;
    const flowStrength = this.parameters.flowStrength.value as number;
    const palette = this.parameters.palette.value as string;
    
    // Generate complexity score based on parameters
    const complexity = Math.round(
      (particleCount / 1000) * 3 +
      (1 / noiseScale) * 2 +
      flowStrength
    );

    // Determine flow pattern type based on noise scale
    let flowPattern: string;
    if (noiseScale < 0.003) {
      flowPattern = 'Turbulent';
    } else if (noiseScale < 0.008) {
      flowPattern = 'Organic';
    } else {
      flowPattern = 'Chaotic';
    }

    // Energy level based on flow strength
    let energy: string;
    if (flowStrength < 1.5) {
      energy = 'Calm';
    } else if (flowStrength < 3) {
      energy = 'Dynamic';
    } else {
      energy = 'Intense';
    }

    return {
      'Algorithm': 'Perlin Flow Field',
      'Particle Count': particleCount,
      'Flow Pattern': flowPattern,
      'Energy Level': energy,
      'Color Palette': palette,
      'Complexity': Math.min(10, complexity)
    };
  }

  protected render(context: GenerationContext): void {
    const { canvas, ctx, width, height, random } = context;
    
    // Get parameters
    const particleCount = this.parameters.particleCount.value as number;
    const noiseScale = this.parameters.noiseScale.value as number;
    const flowStrength = this.parameters.flowStrength.value as number;
    const trailLength = this.parameters.trailLength.value as number;
    const paletteKey = this.parameters.palette.value as string;
    const background = this.parameters.background.value as string;

    // Setup background
    this.setupBackground(ctx, width, height, background);

    // Create noise generator
    const noise = new PerlinNoise(this.hashSeed(context.seed));
    
    // Get color palette
    const palette = PALETTES[paletteKey] || PALETTES.ocean;
    const colors = palette.colors.map(c => new Color(c.r, c.g, c.b));

    // Create particles
    const particles: Particle[] = [];
    for (let i = 0; i < particleCount; i++) {
      particles.push({
        position: new Vec2(
          random.range(0, width),
          random.range(0, height)
        ),
        velocity: new Vec2(0, 0),
        age: 0,
        maxAge: random.integer(100, 300),
        color: random.choice(colors),
        trail: []
      });
    }

    // Animation loop simulation
    const maxFrames = 300;
    ctx.globalCompositeOperation = 'screen';
    
    for (let frame = 0; frame < maxFrames; frame++) {
      const frameAlpha = 1 - (frame / maxFrames) * 0.7; // Fade over time
      
      particles.forEach(particle => {
        // Update particle
        this.updateParticle(particle, noise, noiseScale, flowStrength, width, height, frame);
        
        // Draw trail
        this.drawParticleTrail(ctx, particle, frameAlpha, trailLength);
        
        // Reset particle if too old or out of bounds
        if (particle.age > particle.maxAge || this.isOutOfBounds(particle.position, width, height)) {
          this.resetParticle(particle, random, width, height, colors);
        }
        
        particle.age++;
      });
    }

    // Add final overlay effects
    this.addOverlayEffects(ctx, width, height, random);
  }

  private setupBackground(ctx: CanvasRenderingContext2D, width: number, height: number, style: string): void {
    ctx.fillStyle = style === 'dark' ? '#0a0a0a' : style === 'light' ? '#f8f8f8' : 'transparent';
    if (style !== 'transparent') {
      ctx.fillRect(0, 0, width, height);
    }
  }

  private updateParticle(
    particle: Particle,
    noise: PerlinNoise,
    noiseScale: number,
    flowStrength: number,
    width: number,
    height: number,
    time: number
  ): void {
    // Get flow field direction from noise
    const noiseValue = noise.noise3D(
      particle.position.x * noiseScale,
      particle.position.y * noiseScale,
      time * 0.01
    );
    
    const angle = noiseValue * Math.PI * 2;
    const flowForce = Vec2.fromAngle(angle, flowStrength * 0.1);
    
    // Apply force
    particle.velocity = particle.velocity.add(flowForce);
    
    // Limit velocity
    const maxSpeed = 2;
    if (particle.velocity.magnitude() > maxSpeed) {
      particle.velocity = particle.velocity.normalize().multiply(maxSpeed);
    }
    
    // Update position
    particle.position = particle.position.add(particle.velocity);
    
    // Add to trail
    particle.trail.push(particle.position.clone());
    
    // Apply damping
    particle.velocity = particle.velocity.multiply(0.95);
  }

  private drawParticleTrail(
    ctx: CanvasRenderingContext2D,
    particle: Particle,
    globalAlpha: number,
    maxTrailLength: number
  ): void {
    if (particle.trail.length < 2) return;
    
    // Limit trail length
    if (particle.trail.length > maxTrailLength) {
      particle.trail.shift();
    }
    
    // Draw trail segments
    ctx.strokeStyle = particle.color.toRGBA();
    ctx.lineWidth = 1;
    
    for (let i = 1; i < particle.trail.length; i++) {
      const segmentAlpha = (i / particle.trail.length) * globalAlpha * 0.6;
      const prev = particle.trail[i - 1];
      const curr = particle.trail[i];
      
      ctx.globalAlpha = segmentAlpha;
      ctx.beginPath();
      ctx.moveTo(prev.x, prev.y);
      ctx.lineTo(curr.x, curr.y);
      ctx.stroke();
    }
    
    // Draw particle
    ctx.globalAlpha = globalAlpha;
    ctx.fillStyle = particle.color.toRGBA();
    ctx.beginPath();
    ctx.arc(particle.position.x, particle.position.y, 1, 0, Math.PI * 2);
    ctx.fill();
  }

  private isOutOfBounds(position: Vec2, width: number, height: number): boolean {
    const margin = 50;
    return position.x < -margin || position.x > width + margin ||
           position.y < -margin || position.y > height + margin;
  }

  private resetParticle(
    particle: Particle,
    random: any,
    width: number,
    height: number,
    colors: Color[]
  ): void {
    particle.position = new Vec2(
      random.range(0, width),
      random.range(0, height)
    );
    particle.velocity = new Vec2(0, 0);
    particle.age = 0;
    particle.maxAge = random.integer(100, 300);
    particle.color = random.choice(colors);
    particle.trail = [];
  }

  private addOverlayEffects(
    ctx: CanvasRenderingContext2D,
    width: number,
    height: number,
    random: any
  ): void {
    // Add subtle grain effect
    ctx.globalCompositeOperation = 'overlay';
    ctx.globalAlpha = 0.03;
    
    const imageData = ctx.getImageData(0, 0, width, height);
    const data = imageData.data;
    
    for (let i = 0; i < data.length; i += 4) {
      const grain = (random.next() - 0.5) * 50;
      data[i] += grain;     // R
      data[i + 1] += grain; // G
      data[i + 2] += grain; // B
    }
    
    ctx.putImageData(imageData, 0, 0);
    ctx.globalAlpha = 1;
    ctx.globalCompositeOperation = 'source-over';
  }

  private hashSeed(seed: string): number {
    let hash = 0;
    for (let i = 0; i < seed.length; i++) {
      const char = seed.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash;
    }
    return Math.abs(hash);
  }
}